// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	Author    string `json:"author"`
	CreatedAt string `json:"createdAt"`
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"createdAt"`
}

type WeatherAlert struct {
	ID              string   `json:"id"`
	Region          string   `json:"region"`
	Severity        string   `json:"severity"`
	IssuedAt        string   `json:"issuedAt"`
	Title           string   `json:"title"`
	Description     string   `json:"description"`
	RawData         string   `json:"rawData"`
	AffectedAreas   []string `json:"affectedAreas"`
	Recommendations []string `json:"recommendations"`
}
